application: kneetenzero
version: python
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /.*
  script: oauth.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
