application: kneetenzero
version: go
runtime: go
api_version: go1

handlers:
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico
  - url: /static
    static_dir: static
    application_readable: true
  - url: /.*
    script: _go_app

